### ISSUE TITLE
What version of tensorflow did you use?

### ISSUE THREAD

**Issue by kribby** [LiDan456/Multivariate-Anomaly-Detection-for-Time-Series-Data-with-GANs#9]
Hi 
I have tensorflow 2.0 installed.

When I run
python3 RGAN.py --settings_file kdd99

I get the following error

```

Traceback (most recent call last):
  File "RGAN.py", line 8, in <module>
    import data_utils
  File "/home/ec2-user/MAD-GANs/data_utils.py", line 9, in <module>
    import model
  File "/home/ec2-user/MAD-GANs/model.py", line 11, in <module>
    tf.logging.set_verbosity(tf.logging.ERROR)
AttributeError: module 'tensorflow' has no attribute 'logging'
```

Google searches are suggesting its a problem with tensorflow version 2.0.0

**Comment by kribby** [comment]
I solved this by amending the code:

I replaced 
import tensorflow as tf


with 

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
